### ISSUE TITLE
lets connect

### ISSUE THREAD

**Issue by 0x4007** [singyiu/dropletpool#1]
interested in your work and would like to connect! i found you via marketmake [t.me/pavlovcik](https://t.me/pavlovcik)

**Comment by singyiu** [comment]
Hi @pavlovcik 
Sorry that I did not catch this message. Let me know if you still want to connect.
Closing this issue for now.

**Comment by 0x4007** [comment]
Telegram me? https://t.me/pavlovcik

**Comment by pavlovcik** [comment]
Telegram me? T.me/pavlovcik
